AlfaTestApp/Models/AjaxCodes.cs
namespace AlfaTestApp.Models
{
    public enum AjaxCodes
    {
        Success = 0, 
        Error = 1
    }
}

AlfaTestApp/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlfaTestAppDal;
using AlfaTestApp.Models;

namespace AlfaTestApp.Controllers
{
    public class AuthorController : Controller
    {
        private IDal _dal;

        public AuthorController(IDal dal)
        {
            _dal = dal;
        }

        public ActionResult Index()
        {
            return View("Authors");
        }

        /// <summary>
        ///  страница каталога книг конкретного автора
        /// </summary>        
        public ActionResult AuthorsBooksPage(int authId)
        {

            ViewBag.AuthId = authId;
            return View();
        }

        /// <summary>
        /// Получение данных ajaxом
        /// </summary>        
        public JsonResult GetAuthorsBooksData(int authId)
        {
            try
            {
                var data = _dal.GetAuthorsBooksPageData(authId);
                return Json(new { data, status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error }, JsonRequestBehavior.AllowGet);
            }
        }


        /// <summary>
        /// Получение данных ajaxом
        /// </summary>        
        public JsonResult GetAuthors(int page, int count)
        {
            try
            {
                var data = _dal.GetAuthorsPageData(page, count);
                return Json(new { data, status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Обработчик ajax-запроса на добавление автора
        /// </summary>       
        public JsonResult AddAuthor(string name, string country, string bDate)
        {
            try
            {
                DateTime date;

                if (!DateTime.TryParse(bDate, out date)) throw new Exception("Дата рождения указана в неправильном формате");
                var author = new Authors
                {
                    Name = name,
                    Country = country,
                    BirthDate = date
                };

                var addedAuthor = _dal.AddAuthor(author);
                return Json(new { author = addedAuthor, status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

AlfaTestApp/Controllers/BookController.cs
using System;
using System.Web.Mvc;
using AlfaTestApp.Models;
using AlfaTestAppDal;

namespace AlfaTestApp.Controllers
{
    public class BookController : Controller
    {
        private IDal _dal;

        public BookController(IDal dal)
        {
            _dal = dal;
        }

        // GET: Book
        public ActionResult Index()
        {
            return View("Books");
        }

        /// <summary>
        ///Постраничная подгрузка данных о книгах 
        /// </summary>      
        public JsonResult GetBooks(int page, int count, string searchTerm)
        {
            try
            {
                var data = _dal.GetBooksPageData(page, count, searchTerm);
                return Json(new { data, status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error },JsonRequestBehavior.AllowGet);
            }

        }

        /// <summary>
        /// Обработчик ajax-запроса на добавление автора
        /// </summary>       
        public JsonResult AddBook(BookModel bookModel)
        {
            try
            {
               
                var book = new Books
                {
                   Title = bookModel.title,
                   ShortDesc = bookModel.shortDesc,
                   IssueDate = new DateTime(bookModel.year, 1, 1),
                   AuthorId = bookModel.authorId,
                   ISBNcode = bookModel.ISBNcode,
                   Lang = bookModel.lang                    
                };

                var addedBook = _dal.AddBook(book);
                return Json(new { book = addedBook, status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

AlfaTestApp/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using AlfaTestAppDal;
using AlfaTestApp.Models;

namespace AlfaTestApp.Controllers
{
    public class HomeController : Controller
    {
        private IDal _dal;

        public HomeController(IDal dal)
        {
            _dal = dal;
        }

        public ActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// Cтраница отчета
        /// </summary>        
        public ActionResult ReportPage() {
            return View();
        }

        /// <summary>
        /// Запрос данных отчета
        /// </summary>        
        public JsonResult GetReportData() {
            try
            {
                var data = _dal.GetReportData();
                return Json(new { data, status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Генерация тестовых данных
        /// </summary>        
        public JsonResult GenerateTestData()
        {
            try
            {
                _dal.AddTestData();
                return Json(new { status = AjaxCodes.Success.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { errMessage = ex.Message, status = AjaxCodes.Error }, JsonRequestBehavior.AllowGet);
            }
            
        }
    }
}

AlfaTestApp/Views/Author/Authors.cshtml
@{
    ViewBag.Title = "Authors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">

    <div class="panel-heading">
       <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
            Добавить автора
        </button>
    </div>
    <div class="panel-body">
        <!--ko template: {name: 'paginator', data: $root} -->
        <!--/ko-->
    </div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Страна</th>
                <th>Дата рождения</th>    
                <th></th>          
            </tr>
        </thead>
        <tbody data-bind="foreach: authors">
            <!--ko template: {name: 'author-row-template', data: $data} -->
            <!--/ko-->
        </tbody>
    </table>
    <div class="panel-body">
        <!--ko template: {name: 'paginator', data: $root} -->
        <!--/ko-->
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Добавить автора</h4>
            </div>

            <div class="modal-body">
                <form class="form-horizontal">
                    <fieldset>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Имя</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" placeholder="Имя" data-bind="value: name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Страна</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" placeholder="Страна" data-bind="value: country">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-2 control-label">Дата рождения</label>
                            <div class="col-lg-10">
                                <input type="text" class="form-control" placeholder="Дата рождения" data-bind="value: bDate">
                            </div>
                        </div>
                    </fieldset>
                </form>
                        
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary" data-bind="click: addAuthor">Добавить</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        Html.RenderPartial("Templates");
        Html.RenderPartial("~/Views/Shared/Paginator.cshtml");
    }

    <script src=@Url.Content("~/Scripts/books.authorVm.js")></script>
}

AlfaTestApp/Views/Author/AuthorsBooksPage.cshtml
@{
    ViewBag.Title = "AuthorsBooks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron" data-bind ="with: author">
    <h1 data-bind="text: name"></h1>
    <p class="lead">
        страна: <span data-bind="text: country"></span> <br/>
        дата рождения: <span data-bind="text: birthDate"></span><br/>
    </p>    
    <p class="lead">Книги этого автора представлены в таблице </p>    

    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        Добавить книгу
    </button>
</div>



<div class="panel panel-default">
    <table class="table">
        <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Год издания</th>
                
            </tr>
        </thead>
        <tbody data-bind="foreach: books">
            <!--ko template: {name: 'book-row-template', data: $data} -->
            <!--/ko-->
        </tbody>
    </table>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <fieldset>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">Название</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="Название" data-bind="value: title">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">Краткое описание </label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="Краткое описание" data-bind="value: shortDesc">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">Год издания</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="Год издания" data-bind="value: year">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">Язык</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="Год издания" data-bind="value: lang">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">ISBN</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="код ISBN" data-bind="value: ISBNcode">
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-bind="click: addBook">Добавить</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        Html.RenderPartial("~/Views/Book/Templates.cshtml");
        Html.RenderPartial("~/Views/Shared/Paginator.cshtml");
    }
    <script>
        var booksRepository = booksRepository || {};
        booksRepository.authId = @ViewBag.AuthId;
    </script>
    <script src=@Url.Content("~/Scripts/books.authorBookVm.js")></script>
}

AlfaTestApp/Views/Author/Templates.cshtml
@*Шаблон строки для таблицы авторов*@
<script type="text/html" id="author-row-template">
    <tr>
        <td class="name "
            data-bind="text: name"></td>
        <td class="country "
            data-bind="text: country"></td>
        <td class="birth-date"
            data-bind="text: birthDate"></td>        
        <td>
            <a data-bind="attr: { href: '/catalog/'+ id}">Книги</a>
        </td>
    </tr>
</script>

AlfaTestApp/Views/Book/Books.cshtml
@{
    ViewBag.Title = "Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-default">

<div class="panel-heading">
    <!--ko template: {name: 'search-form', data: $root} -->
    <!--/ko-->
</div>
<div class="panel-body">
    <!--ko template: {name: 'paginator', data: $root} -->
    <!--/ko-->
</div>


<table class="table">
    <thead>
        <tr>
            <th>Название</th>
            <th>Описание</th>
            <th>Год</th>
            <th>Автор</th>   
            <th>ISBN</th>        
        </tr>
    </thead>
    <tbody data-bind="foreach: books">
        <!--ko template: {name: 'book-row-template', data: $data} -->
        <!--/ko-->
    </tbody>
</table>
    <div class="panel-body">
        <!--ko template: {name: 'paginator', data: $root} -->
        <!--/ko-->
    </div>
</div>

@section Scripts{
    @{
        Html.RenderPartial("Templates");
        Html.RenderPartial("~/Views/Shared/Paginator.cshtml");
    }
    <script src=@Url.Content("~/Scripts/books.bookVm.js")></script>
}

AlfaTestApp/Views/Book/Templates.cshtml
@*Шаблон строки информации о книге *@
<script type="text/html" id="book-row-template">
    <tr>
        <td class="title"
             data-bind="text: title"></td>
        <td class="short-desc "
             data-bind="text: shortDesc"></td>
        <td class="issue-year "
             data-bind="text: year"></td>
        <td class="author">
            <a  data-bind="text: authorName, 
                        visible: authorName != '',
                        attr: {href: '/catalog/' + authorId}"></a>
        </td>
        <td class="ISBN col-lg-1" data-bind="text: ISBNcode">
           
        </td>
    </tr>   
</script>

@*Шаблон формы поиска*@
<script type="text/html" id="search-form">
    <div class="row">
        <div class="col-xs-6">
            <div class="input-group">
                <input type="text"
                       class="form-control" placeholder="Search for..."
                       data-bind="value: searchTerm">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Go!</button>
                </span>
            </div>
        </div>
    </div>


</script>

AlfaTestApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">

    <p class="lead">
        В данном тестовом задании реализованы следующие пункты          <br />
        - Постраничный вывод книг и авторов                                     <br />
        - Поиск по книгам (isbn,название, описание)                             <br />
        - Добавление автора                                                     <br />
        - Добавление книги                                                      <br />
        - Страница каталога (инфо о авторе и список  его книг )                 <br />
        - Страница отчета в которой через хранимку агрегируются данные о количестве книг каждого автора и его доли от общега числа книг </br>
        - Генерация тестовых данных
    </p>
    <p><a class="btn btn-primary btn-lg"
          data-bind="   text: createTestDataBtnText,
                        click: createTestData"
          >Cгенерировать тестовые данные </a></p>
</div>

@section Scripts{
   
    <script src=@Url.Content("~/Scripts/сreateTestData.js")></script>
}

AlfaTestApp/Views/Home/ReportPage.cshtml
@{
    ViewBag.Title = "Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="panel panel-default">
    <table class="table">
        <thead>
            <tr>
                <th>Имя автора </th>
                <th>Количество книг</th>
                <th>Доля</th>                
            </tr>
        </thead>
        <tbody data-bind="foreach: reportRows">
            <tr>
                <td data-bind="text: name"></td>
                <td data-bind="text: bookCount"></td>
                <td data-bind="text: share"></td>
            </tr>
        </tbody>
    </table>    
</div>

@section Scripts{
   
    <script src=@Url.Content("~/Scripts/books.reportVm.js")></script>
}

AlfaTestApp/Views/Shared/Paginator.cshtml
@*Шаблон пагинатора*@
<script type="text/html" id="paginator">
    <nav>
        <ul class="pager">
            <li class="previous"
                data-bind="css: {'disabled': currentPage() == 1}">
                <a data-bind="click: previousPage"><span aria-hidden="true">&larr;</span> Туда</a>
            </li>
            <li class="next"><a data-bind="click: nextPage">Сюда <span aria-hidden="true">&rarr;</span></a></li>
        </ul>
    </nav>
</script>

AlfaTestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Книги", "Index", "Book")</li>
                    <li>@Html.ActionLink("Авторы", "Index", "Author")</li>
                    <li>@Html.ActionLink("Отчет", "ReportPage", "Home")</li>
                </ul>
              
            </div>
        </div>
    </div>
    <div class="container body-content" data-bind="with: booksRepository">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    <script>
        var success = '@AlfaTestApp.Models.AjaxCodes.Success';
        var booksRepository = booksRepository || {};

        // url ajax-запросов
        booksRepository.urls = {};
        booksRepository.urls.loadBooks = '@Url.Action("GetBooks",new  {controller = "Book" })';
        booksRepository.urls.loadAuthors = '@Url.Action("GetAuthors",new  {controller = "Author" })';
        booksRepository.urls.loadAuthorsBooks = '@Url.Action("GetAuthorsBooksData", new  {controller = "Author" })';
        booksRepository.urls.loadReportData = '@Url.Action("GetReportData", new  {controller = "Home" })';
        booksRepository.urls.generateTestData = '@Url.Action("GenerateTestData", new  {controller = "Home" })';

        booksRepository.urls.addAuthor = '@Url.Action("AddAuthor", new  {controller = "Author" })';
        booksRepository.urls.addBook = '@Url.Action("AddBook", new  {controller = "Book" })';

    </script>
    @RenderSection("scripts", required: false)

    <script>
        ko.applyBindings(booksRepository);
    </script>
</body>
</html>